# Generated by Django 3.0.11 on 2021-01-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
